import "./globals.css";

export const metadata = {
  title: "FULL STACK TODO LIST APP WITH NEXT.JS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/axcelimg.png" />
      <body
        className={` antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
