import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";
import GoTop from "@/components/GoTop";

export const metadata = {
  title: "FULL STACK TODO LIST APP WITH NEXT.JS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/axcelimg.png" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css"
          integrity="sha512-DxV+EoADOkOygM4IR9yXP8Sb2qwgidEmeqAEmDKIOfPRQZOWbXCzLC6vjbZyy0vPisbH2SyW27+ddLVCN+OMzQ=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </head>
      <body className={`antialiased `}>
        <Header />
        <div className="min-h-125">{children}</div>
        <GoTop />
        <Footer />
      </body>
    </html>
  );
}
