import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "FULL STACK TODO LIST APP WITH NEXT.JS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/axcelimg.png" />
      <body className={`antialiased `}>
        <Header />
        <div className="min-h-125">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
