let todoData = [
  { id: 100, courseCode: 201, course: "Physics", Dept: "Engineering" },
  { id: 101, courseCode: 202, course: "Mathematics", Dept: "Science" },
  { id: 102, courseCode: 203, course: "Chemistry", Dept: "Science" },
  // { id: 103, courseCode: 204, course: "Computer Science", Dept: "Technology" },
  // { id: 104, courseCode: 205, course: "Economics", Dept: "Social Science" },
  // { id: 105, courseCode: 206, course: "Biology", Dept: "Science" },
  // { id: 106, courseCode: 207, course: "Mechanical Engineering", Dept: "Engineering",},
  // { id: 107, courseCode: 208, course: "Civil Engineering", Dept: "Engineering", },
  // { id: 108, courseCode: 209, course: "History", Dept: "Arts" },
  // { id: 109, courseCode: 210, course: "Philosophy", Dept: "Arts" },
  // { id: 110, courseCode: 211, course: "Electrical Engineering", Dept: "Engineering", },
  // { id: 111, courseCode: 212, course: "Political Science", Dept: "Social Science", },
  // { id: 112, courseCode: 213, course: "Sociology", Dept: "Social Science" },
  // { id: 113, courseCode: 214, course: "Geography", Dept: "Science" },
  // { id: 114, courseCode: 215, course: "Environmental Science", Dept: "Science", },
  // { id: 115, courseCode: 216, course: "Linguistics", Dept: "Arts" },
  // { id: 116, courseCode: 217, course: "Literature", Dept: "Arts" },
  // { id: 117, courseCode: 218, course: "Law", Dept: "Law" },
  // { id: 118, courseCode: 219, course: "Medicine", Dept: "Health Sciences" },
  // { id: 119, courseCode: 220, course: "Nursing", Dept: "Health Sciences" },
  // { id: 120, courseCode: 221, course: "Pharmacy", Dept: "Health Sciences" },
  // { id: 121, courseCode: 222, course: "Accounting", Dept: "Business" },
  // { id: 122, courseCode: 223, course: "Business Administration", Dept: "Business", },
  // { id: 123, courseCode: 224, course: "Marketing", Dept: "Business" },
  // { id: 124, courseCode: 225, course: "Architecture", Dept: "Architecture" },
  // { id: 125, courseCode: 226, course: "Fine Arts", Dept: "Arts" },
  // { id: 126, courseCode: 227, course: "Statistics", Dept: "Science" },
  // { id: 127, courseCode: 228, course: "Information Technology", Dept: "Technology",},
  // { id: 128, courseCode: 229, course: "Cybersecurity", Dept: "Technology" },
  // { id: 129, courseCode: 230, course: "Artificial Intelligence", Dept: "Technology",},
];

export default todoData