let todoData = [
  { id: 100, courseCode: 201, course: "Physics", dept: "Engineering" },
  { id: 101, courseCode: 202, course: "Mathematics", dept: "Science" },
  { id: 102, courseCode: 203, course: "Chemistry", dept: "Science" },
  { id: 103, courseCode: 204, course: "Computer Science", dept: "Technology" },
  { id: 104, courseCode: 205, course: "Economics", dept: "Social Science" },
  { id: 105, courseCode: 206, course: "Biology", dept: "Science" },
  { id: 106, courseCode: 207, course: "Mechanical Engineering", dept: "Engineering",},
  { id: 107, courseCode: 208, course: "Civil Engineering", dept: "Engineering", },
  { id: 108, courseCode: 209, course: "History", dept: "Arts" },
  { id: 109, courseCode: 210, course: "Philosophy", dept: "Arts" },
  { id: 110, courseCode: 211, course: "Electrical Engineering", dept: "Engineering", },
  // { id: 111, courseCode: 212, course: "Political Science", dept: "Social Science", },
  // { id: 112, courseCode: 213, course: "Sociology", dept: "Social Science" },
  // { id: 113, courseCode: 214, course: "Geography", dept: "Science" },
  // { id: 114, courseCode: 215, course: "Environmental Science", dept: "Science", },
  // { id: 115, courseCode: 216, course: "Linguistics", dept: "Arts" },
  // { id: 116, courseCode: 217, course: "Literature", dept: "Arts" },
  // { id: 117, courseCode: 218, course: "Law", dept: "Law" },
  // { id: 118, courseCode: 219, course: "Medicine", dept: "Health Sciences" },
  // { id: 119, courseCode: 220, course: "Nursing", dept: "Health Sciences" },
  // { id: 120, courseCode: 221, course: "Pharmacy", dept: "Health Sciences" },
  // { id: 121, courseCode: 222, course: "Accounting", dept: "Business" },
  // { id: 122, courseCode: 223, course: "Business Administration", dept: "Business", },
  // { id: 123, courseCode: 224, course: "Marketing", dept: "Business" },
  // { id: 124, courseCode: 225, course: "Architecture", dept: "Architecture" },
  // { id: 125, courseCode: 226, course: "Fine Arts", dept: "Arts" },
  // { id: 126, courseCode: 227, course: "Statistics", dept: "Science" },
  // { id: 127, courseCode: 228, course: "Information Technology", dept: "Technology",},
  // { id: 128, courseCode: 229, course: "Cybersecurity", dept: "Technology" },
  // { id: 129, courseCode: 230, course: "Artificial Intelligence", dept: "Technology",},
];

export default todoData