// 'use client'
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import AuthProvider from "./context/AuthProvider";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Crud App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/axcelimg.png" />
      </head>
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen `}
      >
        <AuthProvider>
          <Suspense fallback="loading!!">
            <main className="grid min-h-screen w-full overflow-x-hidden">
              <Header />
              {children}
              <Footer />
            </main>
          </Suspense>
        </AuthProvider>
      </body>
    </html>
  );
}
