import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import AuthProvider from "./context/AuthProvider";
import { Suspense } from "react";


export const metadata = {
  title: "TODO LIST APP WITH NEXT.JS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/axcelimg.png" />
      </head>
      <body
        suppressHydrationWarning={true}
        className={`antialiased min-h-screen `}
      >
        <AuthProvider>
          <Suspense fallback="loading!!">
            <main className="grid min-h-screen w-full overflow-x-hidden">
              <Header />
              {children}
              <Footer />
            </main>
          </Suspense>
        </AuthProvider>
      </body>
    </html>
  );
}
